###############
GPU: [0]
PORT: 4567
MODEL:
  NAME: UNet
  MODE: mlp  #
  ARGS:

TRAIN:
  TOTAL_EPOCHS: 250
  BATCH_SIZE: 16

  PRINT_FRE: 400             ## iter frequency of print
  SAVE: 1                 ## when to start save checkpoints
  SAVE_FRE:  1             ## epoch frequency of save checkpoints
  VAL: 10                  ##when to val
  VAL_FRE:   10          ## epoch frequency of val
  SAVE_IMG: false         ## val nseed save images?
  
  RESUME:    false       ## resume? true or false
  PRETRAIN_MODEL: model_latest.pth       ## pretrain_model: latested or epoch_num
  TRAIN_PS:  128          ## patchsize of train
  VAL_PS:                 ## patchsize of val
  SIGMA_VALUE: 15
  INCH: 1
  LR_RANGE: 0              ##when to start lr_decay

PATH:
  TRAIN_DATASET: /home/hua/Code/DFWB/train/DFWB/
  VAL_DATASET: /home/hua/Code/DFWB/test/

# Optimization arguments.
OPTIM:  #default AdamS
  lr: !!float 1e-3
  betas: [0.9, 0.999]
  eps: !!float 1e-8

# schedual arguments.
SCHE:
  T_max: 1118437
  eta_min: !!float 1e-6

